name: Build EZ AudioMate
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install pyinstaller customtkinter pillow soundfile librosa soxr
      - name: Build executable
        run: python -m PyInstaller --onefile --windowed --name "EZ AudioMate" --icon "OSA_icon.ico" --add-data "white_square_OSA_med.png;." gui.py
      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: EZ-AudioMate-Windows
          path: "dist/EZ AudioMate.exe"
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install pyinstaller customtkinter pillow soundfile librosa soxr
      - name: Build executable
        run: python -m PyInstaller --onefile --windowed --name "EZ AudioMate" --add-data "white_square_OSA_med.png:." gui.py
      - name: Upload Mac executable
        uses: actions/upload-artifact@v4
        with:
          name: EZ-AudioMate-Mac
          path: "dist/EZ AudioMate"
